name: cluster_manager

version: 0.0.1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  collection: ^1.16.0
  google_maps_flutter_platform_interface: ^2.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
